"""
Django settings for test_django1 project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

from configurations import Configuration


class BaseConfiguration(Configuration):
    # Build paths inside the project like this: os.path.join(BASE_DIR, ...)
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    SECRET_KEY = 'qphl#hgeo8r9c4x$4&jjbraqxe63%k=)#+q^5*=5ixl$wh82#('

    DEBUG = True

    ALLOWED_HOSTS = ['*']

    INSTALLED_APPS = [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'django.contrib.postgres',
    ]

    MIDDLEWARE = [
        'django.middleware.security.SecurityMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
    ]

    ROOT_URLCONF = 'test_django1.urls'

    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                ],
            },
        },
    ]

    WSGI_APPLICATION = 'test_django1.wsgi.application'

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

    # DATABASES = {
    #     'default': {
    #         'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #         'NAME': 'test_django1',
    #         'USER': 'user',
    #         'PASSWORD': 'password',
    #         'HOST': 'localhost',
    #         'PORT': '5432',
    #     }
    # }

    AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]

    LANGUAGE_CODE = 'en-us'

    TIME_ZONE = 'UTC'

    USE_I18N = True

    USE_L10N = True

    USE_TZ = True

    STATIC_URL = '/static/'
    STATIC_ROOT = "/static"
    STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")

    SITE_URL = 'http://localhost:8000'

    # AUTH_USER_MODEL = 'authe.MainUser'
    # AUTHENTICATION_BACKENDS = (
    #     ('django.contrib.auth.backends.ModelBackend'),
    # )
    # AUTH_TOKEN_HEADER_NAME = ["AUTH_TOKEN", "HTTP_AUTH_TOKEN", "Auth-Token"]

    # EMAIL_HOST = 'email-smtp.eu-west-1.amazonaws.com'
    # EMAIL_HOST_USER = 'AKIAJAP6EQ2VKDU6WYTA'
    # EMAIL_HOST_PASSWORD = 'Ah5u0X5xycsFGUFCQx6ChgLFrcP2Rwg7pW3tYgr3reHD'
    # FROM_EMAIL = u'test_django1 Team <votemcompany@gmail.com>'
    # EMAIL_PORT = 587
    # EMAIL_USE_TLS = True

    # FRONT_URL = ''
    # PASSWORD_RESET_URL = FRONT_URL + "/reset/{token}"

    LIMIT = 10

    BROKER_URL = 'amqp://guest:guest@localhost:5672//'
    CELERYBEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

    ADMINS = (
    )


class Dev(BaseConfiguration):
    DEBUG = True
    ALLOWED_HOSTS = ['*']
    SITE_URL = ""
    STATIC_ROOT = "/static"
    MEDIA_ROOT = "/media"


class Production(BaseConfiguration):
    DEBUG = False
    ALLOWED_HOSTS = ['']
    SITE_URL = ""
